"""empty message

Revision ID: 36e82891f99c
Revises: 
Create Date: 2018-08-18 13:02:02.747066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e82891f99c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True))
    op.add_column('users', sa.Column('is_anonymous', sa.Boolean(), server_default='true', nullable=True))
    op.add_column('users', sa.Column('is_authenticated', sa.Boolean(), server_default='true', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_authenticated')
    op.drop_column('users', 'is_anonymous')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
